//消息处理程序头文件
#pragma once
INT_PTR CALLBACK    About(HWND, UINT, WPARAM, LPARAM);
// 将 Tools 从对话过程改为窗口过程
LRESULT CALLBACK    ToolsWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK    GuideWndProc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK    StyleWndproc(HWND, UINT, WPARAM, LPARAM);
LRESULT CALLBACK    FilesTabSubclassProc(HWND, UINT, WPARAM, LPARAM, UINT_PTR, DWORD_PTR);
LRESULT CALLBACK    ClothTabSubclassProc(HWND, UINT, WPARAM, LPARAM, UINT_PTR, DWORD_PTR);
INT_PTR CALLBACK    Explain(HWND, UINT, WPARAM, LPARAM);